services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    env_file: ./server/.env
    ports:
      - 5432:5432
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 8000:8000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/server:/app
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    ports:
      - 3000:3000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/client:/app
      - ignore:/app/node_modules

volumes:
  ignore:
