# Generated by Django 5.0.6 on 2024-07-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="password_hash",
            new_name="password",
        ),
    ]
