# Generated by Django 5.0.6 on 2024-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="avatar_url",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
