# Generated by Django 5.0.6 on 2024-07-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.RemoveField(
            model_name="bids",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="budget",
        ),
        migrations.AddField(
            model_name="bids",
            name="price",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="tasks",
            name="category",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tasks",
            name="estimated_price",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tasks",
            name="estimated_time",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="users",
            name="user_role",
            field=models.CharField(default="", max_length=50),
        ),
    ]
