# Generated by Django 5.0.7 on 2024-07-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="location",
        ),
        migrations.CreateModel(
            name="TaskLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suburb", models.CharField(default="", max_length=255)),
                ("state", models.CharField(default="", max_length=255)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="app.tasks",
                    ),
                ),
            ],
        ),
    ]
