# Generated by Django 5.0.7 on 2024-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_tasks_location_tasklocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="status",
            field=models.CharField(default="BIDDING", max_length=50),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.CharField(default="BIDDING", max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
