# Generated by Django 5.0.6 on 2024-07-17 09:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_profiles_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="avatar_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.get_avatar_upload_path
            ),
        ),
    ]
