# Generated by Django 5.0.6 on 2024-07-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_users_options_remove_bids_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="estimated_price",
            new_name="budget",
        ),
    ]
