# Generated by Django 5.0.7 on 2024-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_bids_status_alter_tasks_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="tips",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
